#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-polly-proxy"
main = "src/index.js"
compatibility_date = "2024-06-05"
compatibility_flags = ["nodejs_compat"]
rules = [
  { type = "Data", globs = ["../static/*"], fallthrough = true }
]

[vars]
AWS_HOST = 'https://polly.us-east-1.amazonaws.com'